/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiList;

import domain.Cliente;
import domain.Distribuicao;
import domain.Fabrica;
import domain.Mercado;
import domain.Transporte;
import domain.Vacina;
import domain.Veiculo;
import guiregister.CadastroClienteView;
import guiregister.CadastroDistribuicaoView;
import guiregister.CadastroFabricaView;
import guiregister.CadastroMercadoView;
import guiregister.CadastroTransporteView;
import guiregister.CadastroVacinaView;
import java.util.ArrayList;

/**
 *
 * @author rfcjo
 */
public class PrincipalView extends javax.swing.JFrame {
    private ArrayList<Cliente> cliente; 
    private ArrayList<Distribuicao> distribuicao; 
    private ArrayList<Fabrica> fabrica; 
    private ArrayList<Mercado> mercado; 
    private ArrayList<Transporte> transporte; 
    private ArrayList<Veiculo> veiculo; 
    private ArrayList<Vacina> vacina; 
    
    
    public ArrayList<Vacina> getVacina(){
        return this.vacina;
    }
    public ArrayList<Cliente> getCliente(){
        return this.cliente;
    }
    public ArrayList<Distribuicao> getDistribuicao(){
        return this.distribuicao;
    }
    public ArrayList<Fabrica> getFabrica(){
        return this.fabrica;
    }
    public ArrayList<Mercado> getMercado(){
        return this.mercado;
    }
    public ArrayList<Transporte> getTransporte(){;;
        return this.transporte;
    }
    public ArrayList<Veiculo> getVeiculo(){
        return this.veiculo;
    }
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        this.vacina = new ArrayList<Vacina>();
        this.cliente = new ArrayList<Cliente>();
        this.fabrica = new ArrayList<Fabrica>();
        this.mercado = new ArrayList<Mercado>();
        this.transporte = new ArrayList<Transporte>();
        this.vacina = new ArrayList<Vacina>();
        this.distribuicao = new ArrayList<Distribuicao>();
        
        initComponents();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mbMercado = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        miCadastroMercado = new javax.swing.JMenuItem();
        miCadastroTransporte = new javax.swing.JMenuItem();
        miCadastroCliente = new javax.swing.JMenuItem();
        miCadastroVacina = new javax.swing.JMenuItem();
        miCadastroFabrica = new javax.swing.JMenuItem();
        miCadastroDistribuicao = new javax.swing.JMenuItem();
        mnMercado = new javax.swing.JMenu();
        miMercado = new javax.swing.JCheckBoxMenuItem();
        miDistribuicao = new javax.swing.JCheckBoxMenuItem();
        miCliente = new javax.swing.JCheckBoxMenuItem();
        miVacina = new javax.swing.JCheckBoxMenuItem();
        miFabrica = new javax.swing.JCheckBoxMenuItem();
        miTransporte = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Inicial");

        mnCadastro.setText("Cadastro");
        mnCadastro.setMargin(new java.awt.Insets(0, 5, 0, 5));

        miCadastroMercado.setText("Mercado");
        miCadastroMercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroMercadoActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroMercado);

        miCadastroTransporte.setText("Transporte");
        miCadastroTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroTransporteActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroTransporte);

        miCadastroCliente.setText("Cliente");
        miCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroClienteActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroCliente);

        miCadastroVacina.setText("Vacina");
        miCadastroVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroVacinaActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroVacina);

        miCadastroFabrica.setText("Fabrica");
        miCadastroFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroFabricaActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroFabrica);

        miCadastroDistribuicao.setText("Distribuição");
        miCadastroDistribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroDistribuicaoActionPerformed(evt);
            }
        });
        mnCadastro.add(miCadastroDistribuicao);

        mbMercado.add(mnCadastro);

        mnMercado.setText("Relatório de Classes");
        mnMercado.setMargin(new java.awt.Insets(0, 2, 0, 5));

        miMercado.setSelected(true);
        miMercado.setText("Mercado");
        miMercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMercadoActionPerformed(evt);
            }
        });
        mnMercado.add(miMercado);

        miDistribuicao.setSelected(true);
        miDistribuicao.setText("Distribuição");
        miDistribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDistribuicaoActionPerformed(evt);
            }
        });
        mnMercado.add(miDistribuicao);

        miCliente.setSelected(true);
        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        mnMercado.add(miCliente);

        miVacina.setSelected(true);
        miVacina.setText("Vacina");
        miVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVacinaActionPerformed(evt);
            }
        });
        mnMercado.add(miVacina);

        miFabrica.setSelected(true);
        miFabrica.setText("Fabrica");
        miFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFabricaActionPerformed(evt);
            }
        });
        mnMercado.add(miFabrica);

        miTransporte.setSelected(true);
        miTransporte.setText("Transporte");
        miTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransporteActionPerformed(evt);
            }
        });
        mnMercado.add(miTransporte);

        mbMercado.add(mnMercado);

        setJMenuBar(mbMercado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Cadastro
    
    private void miCadastroMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroMercadoActionPerformed
        CadastroMercadoView cadMercadoView = new CadastroMercadoView(this);
        cadMercadoView.setVisible(true);
    }//GEN-LAST:event_miCadastroMercadoActionPerformed

    private void miCadastroTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroTransporteActionPerformed
        CadastroTransporteView cadTransporteView = new CadastroTransporteView();
        cadTransporteView.setVisible(true);
    }//GEN-LAST:event_miCadastroTransporteActionPerformed

    private void miCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroClienteActionPerformed
        CadastroClienteView cadClienteView = new CadastroClienteView(this);
        cadClienteView.setVisible(true);
    }//GEN-LAST:event_miCadastroClienteActionPerformed

    private void miCadastroFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroFabricaActionPerformed
        CadastroFabricaView cadFabricaView = new CadastroFabricaView(this);
        cadFabricaView.setVisible(true);
    }//GEN-LAST:event_miCadastroFabricaActionPerformed

    private void miCadastroVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroVacinaActionPerformed
        CadastroVacinaView cadVacinaView = new CadastroVacinaView(this);
        cadVacinaView.setVisible(true);
    }//GEN-LAST:event_miCadastroVacinaActionPerformed

    private void miCadastroDistribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroDistribuicaoActionPerformed
        CadastroDistribuicaoView cadDistribuicaoView = new CadastroDistribuicaoView(this);
        cadDistribuicaoView.setVisible(true);   
    }//GEN-LAST:event_miCadastroDistribuicaoActionPerformed

    // View
    
    
    private void miMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMercadoActionPerformed
        MercadoView listMercadoView = new MercadoView(this);
        listMercadoView.setVisible(true);
    }//GEN-LAST:event_miMercadoActionPerformed

    private void miDistribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDistribuicaoActionPerformed
        DistribuicaoView listDistribuicaoView = new DistribuicaoView(this);
        listDistribuicaoView.setVisible(true);
    }//GEN-LAST:event_miDistribuicaoActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        ClienteView listClienteView = new ClienteView(this);
        listClienteView.setVisible(true);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVacinaActionPerformed
        VacinaView listVacinaView = new VacinaView(this);
        listVacinaView.setVisible(true);
    }//GEN-LAST:event_miVacinaActionPerformed

    private void miFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFabricaActionPerformed
        FabricaView listFabricaView = new FabricaView(this);
        listFabricaView.setVisible(true);
    }//GEN-LAST:event_miFabricaActionPerformed

    private void miTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransporteActionPerformed
        TransporteView listTransporteView = new TransporteView(this);
        listTransporteView.setVisible(true);
    }//GEN-LAST:event_miTransporteActionPerformed
        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar mbMercado;
    private javax.swing.JMenuItem miCadastroCliente;
    private javax.swing.JMenuItem miCadastroDistribuicao;
    private javax.swing.JMenuItem miCadastroFabrica;
    private javax.swing.JMenuItem miCadastroMercado;
    private javax.swing.JMenuItem miCadastroTransporte;
    private javax.swing.JMenuItem miCadastroVacina;
    private javax.swing.JCheckBoxMenuItem miCliente;
    private javax.swing.JCheckBoxMenuItem miDistribuicao;
    private javax.swing.JCheckBoxMenuItem miFabrica;
    private javax.swing.JCheckBoxMenuItem miMercado;
    private javax.swing.JCheckBoxMenuItem miTransporte;
    private javax.swing.JCheckBoxMenuItem miVacina;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnMercado;
    // End of variables declaration//GEN-END:variables
}
